### ==================================================================
### AUTHENTICATION
### ==================================================================

### 1. Rejestracja Pracownika (Jednorazowo)
POST http://localhost:3001/auth/register
Content-Type: application/json

{
  "email": "admin@sklep.pl",
  "password": "tajnehaslo123",
  "role": "EMPLOYEE"
}

### 2. Logowanie (Pobranie tokenów)
# Skopiuj "accessToken" z odpowiedzi!
POST http://localhost:3001/auth/login
Content-Type: application/json

{
  "email": "admin@sklep.pl",
  "password": "tajnehaslo123"
}

### 3. Odświeżanie tokenu (Gdy Access wygaśnie)
# Użyj "refreshToken" z odpowiedzi logowania
POST http://localhost:3001/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzY0MTk5MzY1LCJleHAiOjE3NjQ4MDQxNjV9.RAA8Y6E1eAle9hPfJbOfXtSjGdjwxwSqP-n1ODIxZeI"
}

### ==================================================================
### PROTECTED ROUTES (Wymagają tokena)
### ==================================================================

### Próba dodania produktu BEZ tokena (Powinien być błąd 401)
POST http://localhost:3001/products
Content-Type: application/json

{ "name": "Test", "unitPrice": 10, "categoryId": 1 }


### Dodanie produktu Z TOKENEM (Powinno zadziałać)
# Zastąp 'TU_WKLEJ_TOKEN' tym, co dostałeś przy logowaniu
POST http://localhost:3001/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6IkVNUExPWUVFIiwiaWF0IjoxNzY0MzY5Mzk3LCJleHAiOjE3NjQzNzI5OTd9.pSCK2ns8uAkEwpdjAF2h2ctW_cBK4dlrauKo70P8XDU

{
  "name": "Shovel",
  "description": "Just a simple shovel",
  "unitPrice": 134.99,
  "unitWeight": 2.00,
  "categoryId": 4
}